name: Push to ECR

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with the branch name you want to trigger on

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          registry: 446983553642.dkr.ecr.us-east-1.amazonaws.com/github-actions 
         
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build the Docker image
        run: |
          docker build -t github-actions .
          docker tag github-actions:latest 446983553642.dkr.ecr.us-east-1.amazonaws.com/github-actions:latest

      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 446983553642.dkr.ecr.us-east-1.amazonaws.com
          docker push 446983553642.dkr.ecr.us-east-1.amazonaws.com/github-actions:latest
